### PR TITLE
Collector debugging experience improvements

### PR DESCRIPTION
**Pull request by thedrow**
This PR resolves two pain points when debugging story collection.
See commit messages for details.

### CODE REVIEW

**Comment by thedrow** [comment]
Why did the coverage drop?

**Comment by proofit404** [comment]
> Why did the coverage drop?

Because codecov is an unreliable service these days.

**Comment by proofit404** [comment]
> This PR resolves two pain points when

Could you create two issues to explain this pain points? Steps to reproduce for example. 

> debugging story collection.

How frequently you need to debug the story collection step? I'm surprised it is a problem at all. Why not use the representation of the class attribute when the collection step ends?

**Comment by thedrow** [comment]
> > This PR resolves two pain points when
> 
> Could you create two issues to explain this pain points? Steps to reproduce for example.

Sure but it feels a rather large investment for such a small feature.

> > debugging story collection.
> 
> How frequently you need to debug the story collection step? I'm surprised it is a problem at all. Why not use the representation of the class attribute when the collection step ends?

While developing this library? A lot.
When something goes wrong for the user during collection because of a bug. These will happen.

It's nice to have and it saves me from including this code every time I work on this library.

**Comment by proofit404** [comment]
I don't want to merge this weird code to support the debugger with that strange behavior.
PDB, hunter, and manhole do not have this behavior.
If there is a line in the Python language specification related to it, please point me to it.
I think it's better to report that issue to the PyCharm bug tracker.

**Pull request closed without merging**
