### PR TITLE
Use a pytest plugin to integrate with azurepipelines

### PR DESCRIPTION
**Pull request by thedrow**
This plugin should display test results in the UI.
Let's see how it works...

### CODE REVIEW

**Comment by thedrow** [comment]
Test results are now published in the checks tab which is super cool :)

**Comment by proofit404** [comment]
Thanks for your contribution!

I really appreciate it :tada: 

We have some tests to keep our configuration in a consistent way. Tox requirements should have a proper alphabetic order.

Also, we follow semantic release guidelines for our commit messages. Please, rebase and force push with something like `ci: add pytest plugin to integrate with azure pipelines`.

As always it's my failure to document things. Sorry for that :disappointed: 

Best regards,
Artem.

P.S. It would be really cool if the same PR'll be copied into `dependencies`, `mappers`, and `editors` repositories :pray:

**Comment by thedrow** [comment]
Done.
I'll try my best to apply this patch to all of our projects.

**Comment by proofit404** [comment]
Thanks :tada: :cake: :tada:

**Pull request merged**
