### PR TITLE
Fix MyPy environment installation error in CI

### PR DESCRIPTION
**Pull request by thedrow**
Just trying to help a bit to #187.

According to the [release notes](https://github.com/typeddjango/django-stubs/releases/tag/1.0.1) on django-stubs 1.0.1 psycopg2 is no longer a dependency which means we don't have to set up the environment to install it.

### CODE REVIEW

**Comment by proofit404** [comment]
Hi, thanks for your contribution.

I don't understand what this fix is trying to solve.

We always use the most recent packages so we don't need to lock versions of anything.

If something doesn't work with the new stubs, mypy, pytest, etc, we should fix our project accordingly.

Best regards,
Artem.

**Comment by thedrow** [comment]
Well mypy didn't run because django-stubs used to depend on psycopg2 which wasn't built on our CI system due to the lack of libpq.
This ensures that we pick a version of django-stubs which does not depend on psycopg2.

**Comment by proofit404** [comment]
If I understand correctly, all new builds will use the most recent packages. Even without pin of the version. Am I wrong?

**Comment by thedrow** [comment]
You are right but we don't want to install psycopg2 anyway and on older tox environments it means that we will run the tests without reinstalling the virtual environment.

I guess it's your call.
I prefer it this way.

**Comment by proofit404** [comment]
I think it contradicts with https://github.com/dry-python/stories/issues/186

**Pull request closed without merging**
