### PR TITLE
support rescue when failed

### PR DESCRIPTION
**Pull request by zen-xu**
Hi @proofit404, I think **stories** is a great repo。
But error handling is weak, so I open this request。

```python
from stories import story, arguments, Failure, rescue, Result

class Demo:

    @story
    @arguments("arg")
    def apply(I):
        I.find

    def find(self, ctx):
        return Failure("crash")

    @rescue(find, "crash")
    def _(self, ctx):
        return Result("OK")

Demo.apply.failures(["crash"])

Demo().apply("xxx")
# "OK"
```

### CODE REVIEW

**Comment by proofit404** [comment]
Hi, @zen-xu 

Thanks for your time you've taken to make this contribution!

Could you explain the reasons you want to make it this way?

What business logic patterns you'll be able to express if the library supports such syntax?

In my personal opinion at that point I would prefer to use an internal state of the story together with `Skip` marker. But I'm open to discussion.

P.S. it's necessary to write tests and documentation before we could merge.

P.S.S. What do you think about https://github.com/dry-python/stories/issues/76? Maybe it could solve the problem you're trying to fix.

Have a good day :tada: 

Best regards, Artem.

**Comment by zen-xu** [comment]
This is just my **Tracer Bullet** (from *The Pragmatic Programmer*). I'll improve it if you think this is a good idea ^-^.

### Reason:
I can't ensure each business logic pattern will return `Success`, if it failed the story will just return `Failure`.  Some `Failure` may cannot to handle, so just raise exception, but some `Failure` can be rescued, so I need to handle `Failure` out of the story, and recall the story. So I think may be can just handle `Failure` in the story.

P.S. I don't think #76 is a good way to handle `Failure`

**Comment by proofit404** [comment]
Let's start with the example.

Could you provide a real story with business rules handled by the proposed technique?

Best regards,
Artem.

**Comment by proofit404** [comment]
Looks like it's going nowhere :'(

Feel free to reopen the PR if you find time to finish it.

**Pull request closed without merging**
